name: test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install pytest-cov
          pip install coveralls
      - name: Test with pytest and get coverage
        env: 
          COVERALLS_REPO_TOKEN: InCVAbK1LwdqoUNicTvjLjbbETEFnlmSI
        run: |
          pytest --cov=. tests
          coverage report --fail-under=65
          coveralls


